name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Adjust the Python version as needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pymongo scikit-learn pandas numpy

      - name: Set environment variables
        run: |
          echo "MONGO_USER=${{ secrets.MONGO_USER }}" >> $GITHUB_ENV
          echo "MONGO_PASS=${{ secrets.MONGO_PASS }}" >> $GITHUB_ENV
          echo "MONGO_CLUSTER=${{ secrets.MONGO_CLUSTER }}" >> $GITHUB_ENV
          echo "MONGO_AUTH_DB=${{ secrets.MONGO_AUTH_DB }}" >> $GITHUB_ENV

      - name: Run script
        env:
          MONGO_USER: ${{ secrets.MONGO_USER }}
          MONGO_PASS: ${{ secrets.MONGO_PASS }}
          MONGO_CLUSTER: ${{ secrets.MONGO_CLUSTER }}
          MONGO_AUTH_DB: ${{ secrets.MONGO_AUTH_DB }}
        run: python app.py
